spring.application.name: demo

spring:
  config:
    import: optional:configserver:http://localhost:8888/

message: default-local

---
spring:
  profiles:
    active:
      on-profile: test3

message: test3-local

---
spring:
  profiles:
    active:
      on-profile: test10

message: test10-local
