spring.application.name: demo

spring:
  config:
    import: optional:configserver:http://localhost:8888/

message: default-local

---
spring:
  config:
    activate:
      on-profile: test3

message: test3-local

---
spring:
  config:
    activate:
      on-profile: test10

message: test10-local
